language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t simple-node .
  - docker tag simple-node vmlicona/simple-node:latest

after_success:
  - echo d5g4buun4m | docker login -u vmlicona --password-stdin
  - docker push vmlicona/simple-node
